server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://grafana-loki:3100/loki/api/v1/push


scrape_configs:
  - job_name: service-a-logs
    static_configs:
    - targets:
        - localhost
      labels:
        job: service-a
        __path__: /app/srv-a/logs/*log
  - job_name: service-b-logs
    static_configs:
    - targets:
        - localhost
      labels:
        job: service-b
        __path__: /app/srv-b/logs/*log
  - job_name: service-c-logs
    static_configs:
    - targets:
        - localhost
      labels:
        job: service-c
        __path__: /app/srv-c/logs/*log