{
 "title": "Apache Logs and Metrics",
 "description": "Visualize apache logs.",
 "tags": [
  "Apache2",
  "Logs"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": "SHOW TAG VALUES WITH KEY = \"host\" where \"resp_code\" =~ /./"
   },
   {
    "name": "code",
    "label": "Response code",
    "query": "SHOW TAG VALUES WITH KEY = \"resp_code\" where host =~ /^$server$/"
   },
   {
    "name": "verb",
    "label": "Verb",
    "query": "SHOW TAG VALUES WITH KEY = \"verb\" where host =~ /^$server$/ and resp_code =~ /^$code$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Code $code responses",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"request\") \nFROM \"tail\" \nWHERE \"host\" =~ /^$server$/ AND \"resp_code\" =~ /^$code$/ AND verb =~ /$verb$/ AND \"request\" !~ /\\/server-status/ \nAND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response average size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"resp_bytes\") FROM \"tail\" WHERE \"host\" =~ /^$server$/ AND \"resp_code\" =~ /^$code$/ AND verb =~ /$verb$/ AND \"request\" !~ /\\/server-status/ AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "99 percentile size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"resp_bytes\",99) FROM \"tail\" WHERE \"host\" =~ /^$server$/ AND \"resp_code\" =~ /^$code$/ AND verb =~ /$verb$/  AND \"request\" !~ /\\/server-status/ AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max response size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"resp_bytes\") FROM \"tail\" WHERE \"host\" =~ /^$server$/ AND \"resp_code\" =~ /^$code$/ AND verb =~ /$verb$/  AND \"request\" !~ /\\/server-status/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Status Code Distribution",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "resp_code" ], "type": "tag" }
     ],
     "measurement": "tail",
     "query": "SELECT count(agent) as total \nFROM \"tail\" \nWHERE (\"host\" =~ /^$server$/ AND \"resp_code\" =~ /^$code$/ AND verb =~ /$verb$/ AND \"request\" !~ /\\/server-status/) \nAND $timeFilter GROUP BY resp_code",
     "select": [
      [
       { "params": [ "agent" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "resp_code", "operator": "=~", "value": "/^$code$/" }
     ]
    }
   ]
  },
  {
   "title": "Verb Request Distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "verb" ], "type": "tag" }
     ],
     "measurement": "tail",
     "query": "SELECT count(agent) as total FROM \"tail\" WHERE (\"host\" =~ /^$server$/ AND \"resp_code\" =~ /^$code$/ AND verb =~ /$verb$/ AND \"request\" !~ /\\/server-status/) AND $timeFilter GROUP BY \"verb\"",
     "select": [
      [
       { "params": [ "agent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "resp_code", "operator": "=~", "value": "/^$code$/" }
     ]
    }
   ]
  },
  {
   "title": "Apache Logs",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "SELECT  client_ip as Client, agent as Agent, referrer as Referer, request as Request, resp_code as Response, verb as Verb, http_version as \"HTTP Version\" \nFROM \"tail\" \nWHERE host =~ /$server$/ AND resp_code =~ /$code$/ AND verb =~ /$verb$/ AND \n$timeFilter AND \"request\" !~ /\\/server-status/ fill(null)"
    }
   ]
  }
 ]
}